#!/bin/bash

# Script para configurar Supabase Storage
# Ejecutar después de añadir las keys al .env

echo "🚀 Configurando Supabase Storage para ExtraSchools"
echo ""
echo "📋 Pasos a seguir:"
echo ""
echo "1️⃣  Ve a tu dashboard de Supabase:"
echo "   👉 https://supabase.com/dashboard/project/dsgqgircnjqlvodmgqla"
echo ""
echo "2️⃣  Ve a la sección 'Project Settings' > 'API'"
echo "   👉 https://supabase.com/dashboard/project/dsgqgircnjqlvodmgqla/settings/api"
echo ""
echo "3️⃣  Copia estas keys y añádelas al archivo .env:"
echo ""
echo "   NEXT_PUBLIC_SUPABASE_URL=\"https://dsgqgircnjqlvodmgqla.supabase.co\""
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=\"eyJhbGc...\" (copia 'anon public')"
echo "   SUPABASE_SERVICE_ROLE_KEY=\"eyJhbGc...\" (copia 'service_role')"
echo ""
echo "4️⃣  Ve a 'Storage' en el menú lateral"
echo "   👉 https://supabase.com/dashboard/project/dsgqgircnjqlvodmgqla/storage/buckets"
echo ""
echo "5️⃣  Crea un nuevo bucket:"
echo "   • Nombre: uploads"
echo "   • Public: ✅ SÍ (marca esta opción)"
echo "   • File size limit: 2MB"
echo "   • Allowed MIME types: image/jpeg, image/png, image/webp, image/gif"
echo ""
echo "6️⃣  Reinicia el servidor de desarrollo:"
echo "   npm run dev"
echo ""
echo "✅ ¡Listo! Las imágenes se subirán automáticamente a Supabase Storage"
echo ""
